"""Dashboard route: Memory Pool MCP over Streamable HTTP (Plan 007).

Mounts the Agentic Memory system as an MCP endpoint at ``/api/memory-pool/mcp``
via FastMCP's Streamable HTTP transport.  A ``MemoryPool`` manages one
AgenticMemorySystem instance per unique plan hash ID.

Plan isolation is driven by the **URL query string**::

    http://localhost:3366/api/memory-pool/mcp?plan_id=50d1334520e4

The ``plan_id`` is the 12-char SHA256 hash generated by the dashboard when
a plan is created.  ``init.ps1`` patches the URL with the plan_id at
runtime and creates a symlink from ``project/.memory`` to the centralized
storage at ``~/.ostwin/memory/<plan_id>/``.

Storage layout::

    ~/.ostwin/memory/
    ├── _global/           ← default (no plan_id)
    ├── 50d1334520e4/      ← plan hash ID
    └── da26d173d446/      ← another plan

When the URL omits ``plan_id``, the ``_global`` namespace is used.

The stdio transport in ``mcp_server.py`` is **not** affected — it continues
to work for agents that prefer the legacy per-process model.
"""

from __future__ import annotations

import asyncio
import contextvars
import json
import logging
import os
import sys
import uuid
from typing import Any, Optional
from urllib.parse import parse_qs

from pathlib import Path

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Imports from the co-located agentic_memory package
# ---------------------------------------------------------------------------
from dashboard.agentic_memory.pool_config import PoolConfig, load_pool_config  # noqa: E402
from dashboard.agentic_memory.memory_pool import MemoryPool  # noqa: E402

# ---------------------------------------------------------------------------
# Centralized memory storage — mirrors knowledge module pattern
# ---------------------------------------------------------------------------
MEMORY_BASE_DIR: Path = Path(os.environ.get("OSTWIN_MEMORY_DIR", str(Path.home() / ".ostwin" / "memory")))
DEFAULT_NAMESPACE = "_global"

# ---------------------------------------------------------------------------
# Request-scoped plan_id — set by the ASGI wrapper, read by @mcp.tool()
# ---------------------------------------------------------------------------
_plan_id_ctx: contextvars.ContextVar[str | None] = contextvars.ContextVar(
    "_plan_id_ctx",
    default=None,
)
_active_log_handler: contextvars.ContextVar[Optional[logging.Handler]] = contextvars.ContextVar(
    "_active_log_handler",
    default=None,
)

# ---------------------------------------------------------------------------
# Pool singleton — created once, lives for the dashboard process lifetime
# ---------------------------------------------------------------------------
_pool: Optional[MemoryPool] = None


def _get_pool() -> MemoryPool:
    global _pool
    if _pool is None:
        _pool = MemoryPool(config=load_pool_config())
        logger.info("Memory pool created")
    return _pool


def get_pool() -> MemoryPool:
    """Public accessor for the pool singleton (used by api.py shutdown hook)."""
    return _get_pool()


# ---------------------------------------------------------------------------
# Helper: resolve plan_id to centralized persist directory
# ---------------------------------------------------------------------------
def _resolve_persist_dir(plan_id: str) -> str:
    """Map a plan_id (hash) to a centralized memory directory.

    Storage layout::

        ~/.ostwin/memory/
        ├── _global/           ← default (no plan_id)
        ├── 50d1334520e4/      ← plan hash ID
        └── da26d173d446/      ← another plan

    The plan_id IS the directory name — no ``memory-`` prefix.
    """
    namespace = plan_id if plan_id != DEFAULT_NAMESPACE else DEFAULT_NAMESPACE
    persist_dir = MEMORY_BASE_DIR / namespace
    persist_dir.mkdir(parents=True, exist_ok=True)
    return str(persist_dir)


# ---------------------------------------------------------------------------
# Helper: resolve memory system for a given plan_id
# ---------------------------------------------------------------------------
def _get_memory_for_plan(plan_id: Optional[str] = None):
    """Return the AgenticMemorySystem for the active plan.

    Reads ``plan_id`` from the request-scoped ``_plan_id_ctx`` ContextVar
    (set by ``_PlanIdInjectingApp``).  Falls back to ``_global`` when no
    plan_id is present.

    Also attaches the slot's per-plan log handler so all ``agentic_memory``
    log output for this request goes to ``<persist_dir>/memory.log``.
    """
    resolved = plan_id or _plan_id_ctx.get() or DEFAULT_NAMESPACE
    persist_dir = _resolve_persist_dir(resolved)
    pool = _get_pool()
    slot = pool.get_or_create(persist_dir)
    pool.touch(persist_dir)

    # Attach per-slot log handler for this request.
    # Attach to both "dashboard.agentic_memory" (memory_system.py logs) and
    # the current module logger (save_memory/search_memory logs).
    old_handler = _active_log_handler.get()
    if old_handler:
        for lg_name in ("dashboard.agentic_memory", __name__):
            lg = logging.getLogger(lg_name)
            if old_handler in lg.handlers:
                lg.removeHandler(old_handler)
    if slot.log_handler:
        for lg_name in ("dashboard.agentic_memory", __name__):
            lg = logging.getLogger(lg_name)
            if slot.log_handler not in lg.handlers:
                lg.addHandler(slot.log_handler)
        _active_log_handler.set(slot.log_handler)

    return slot.system


# ---------------------------------------------------------------------------
# FastMCP instance — independent from mcp_server.py's stdio instance
# ---------------------------------------------------------------------------
from mcp.server.fastmcp import FastMCP  # noqa: E402

mcp = FastMCP(
    "Agentic Memory",
    stateless_http=True,
    instructions=(
        "You have access to a persistent memory system that stores knowledge as "
        "interconnected notes organized in a directory tree. Use it to remember "
        "important information, decisions, context, and learnings across "
        "conversations."
    ),
)


# -- Tools -----------------------------------------------------------------
# Thin wrappers that route through the pool.  Plan isolation is handled
# transparently via ``_plan_id_ctx`` (set by the ASGI wrapper from the
# URL query string).  Tools do NOT accept ``plan_id`` — agents never
# need to specify it; the URL ``?plan_id=XXX`` is authoritative.


@mcp.tool()
async def save_memory(
    content: str,
    name: Optional[str] = None,
    path: Optional[str] = None,
    tags: Optional[list[str]] = None,
) -> str:
    """Save a new memory note to the knowledge base.

    Write detailed, comprehensive memories -- not just brief notes. Include context,
    reasoning, examples, trade-offs, and lessons learned. The more detail you provide,
    the more useful the memory will be when retrieved later.

    Good memories are 3-10 sentences and capture:
    - WHAT happened or was decided
    - WHY it matters or was chosen over alternatives
    - HOW it works in practice, with specific details
    - GOTCHAS or edge cases discovered

    The system will automatically:
    - Generate a name and directory path if not provided
    - Extract keywords and tags for semantic search
    - Find and link related existing memories
    - Create a summary for long content (>150 words)

    Args:
        content: The memory content. Be detailed and thorough.
        name: Optional human-readable name (2-5 words). Auto-generated if not provided.
        path: Optional directory path (e.g. "backend/database").
            Auto-generated if not provided.
        tags: Optional list of tags. Auto-generated if not provided.

    Returns:
        JSON with the saved memory's id and status.
    """
    mem = _get_memory_for_plan()
    memory_id = str(uuid.uuid4())

    kwargs: dict[str, Any] = {"id": memory_id}
    if name:
        kwargs["name"] = name
    if path:
        kwargs["path"] = path
    if tags:
        kwargs["tags"] = tags

    resolved_plan = _plan_id_ctx.get() or DEFAULT_NAMESPACE
    logger.info(
        "save_memory [HTTP]: id=%s plan_id=%s content_len=%d",
        memory_id,
        resolved_plan,
        len(content),
    )
    try:
        # add_note does LLM analysis + vector DB + file I/O — must not block event loop
        await asyncio.to_thread(mem.add_note, content, **kwargs)
        logger.info("save_memory [HTTP]: completed id=%s", memory_id)
    except Exception:
        logger.exception("save_memory [HTTP]: failed id=%s", memory_id)
        return json.dumps(
            {"id": memory_id, "status": "error", "message": "Failed to save memory."},
            ensure_ascii=False,
        )

    return json.dumps(
        {
            "id": memory_id,
            "status": "saved",
            "message": "Memory saved with full LLM analysis.",
        },
        ensure_ascii=False,
    )


@mcp.tool()
async def search_memory(query: str, k: int = 5) -> str:
    """Search the knowledge base using natural language.

    Returns the most semantically relevant memories for the query.

    Args:
        query: Natural language search query. Be specific and descriptive.
        k: Maximum number of results to return (default: 5).

    Returns:
        JSON array of matching memories with content, tags, path, and links.
    """
    mem = _get_memory_for_plan()
    logger.info("search_memory [HTTP]: query=%r k=%d plan_id=%s", query, k, _plan_id_ctx.get() or DEFAULT_NAMESPACE)
    # Vector search + file reads are CPU/IO-bound — offload to thread pool
    results = await asyncio.to_thread(mem.search, query, k=k)

    # Read full notes for each result — also I/O bound
    def _read_results(results):
        output = []
        for r in results:
            note = mem.read(r["id"])
            output.append(
                {
                    "id": r["id"],
                    "name": note.name if note else None,
                    "path": note.path if note else None,
                    "content": r["content"],
                    "tags": r.get("tags", []),
                    "keywords": r.get("keywords", []),
                    "links": note.links if note else [],
                    "backlinks": note.backlinks if note else [],
                }
            )
        return output

    output = await asyncio.to_thread(_read_results, results)
    return json.dumps(output, ensure_ascii=False)


@mcp.tool()
async def memory_tree() -> str:
    """Show the full directory tree of all memories.

    Returns:
        Tree-formatted string of the memory directory structure.
    """
    return await asyncio.to_thread(_get_memory_for_plan().tree)


@mcp.tool()
async def delete_memory(memory_id: str) -> str:
    """Delete a specific memory note by its ID.

    Use search_memory or memory_tree first to find the ID of the note
    you want to delete.

    Args:
        memory_id: The UUID of the memory note to delete.

    Returns:
        JSON with the deleted note's id and status.
    """
    mem = _get_memory_for_plan()
    success = await asyncio.to_thread(mem.delete, memory_id)
    if success:
        logger.info("delete_memory [HTTP]: deleted id=%s", memory_id)
        return json.dumps({"id": memory_id, "status": "deleted"})
    else:
        logger.warning("delete_memory [HTTP]: not found id=%s", memory_id)
        return json.dumps({"id": memory_id, "status": "not_found"})


@mcp.tool()
async def grep_memory(pattern: str, flags: Optional[str] = None) -> str:
    """Search memory files using grep (full CLI grep).

    Runs grep on all markdown files in the memory notes directory.

    Examples:
        grep_memory("PostgreSQL")                    -- basic search
        grep_memory("oauth.*token", "-i")            -- case-insensitive regex
        grep_memory("TODO", "-l")                    -- list filenames only

    Args:
        pattern: Search pattern (string or regex depending on flags).
        flags: Optional grep flags as a single string.

    Returns:
        Grep output with paths relative to notes directory.
    """
    import subprocess

    mem = _get_memory_for_plan()
    notes_dir = os.path.join(os.path.abspath(mem.persist_dir), "notes")
    os.makedirs(notes_dir, exist_ok=True)

    cmd = ["grep", "-r", "--include=*.md"]
    if flags:
        # Reuse mcp_server's sanitization logic if available, otherwise basic split
        cmd.extend(flags.split())
    cmd.extend(["-e", pattern, "--", notes_dir])

    def _run_grep():
        try:
            result = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
            if not result.stdout and result.returncode == 1:
                return "No matches found."
            if result.returncode > 1:
                return f"Error: {result.stderr.strip()}"
            return result.stdout.replace(notes_dir + "/", "")
        except subprocess.TimeoutExpired:
            return "Error: grep timed out after 30 seconds."
        except FileNotFoundError:
            return "Error: grep command not found on this system."

    return await asyncio.to_thread(_run_grep)


@mcp.tool()
async def find_memory(args: Optional[str] = None) -> str:
    """Search memory files using find (full CLI find).

    Runs find on the memory notes directory.

    Examples:
        find_memory()                                -- list all files
        find_memory("-name '*.md'")                  -- find by name pattern
        find_memory("-type d")                       -- list directories only

    Args:
        args: Optional find arguments as a single string.

    Returns:
        Find output with paths relative to notes directory.
    """
    import shlex
    import subprocess

    mem = _get_memory_for_plan()
    notes_dir = os.path.join(os.path.abspath(mem.persist_dir), "notes")
    os.makedirs(notes_dir, exist_ok=True)

    cmd = ["find", notes_dir]
    if args:
        cmd.extend(shlex.split(args))

    def _run_find():
        try:
            result = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
            if result.returncode != 0 and result.stderr:
                return f"Error: {result.stderr.strip()}"
            if not result.stdout.strip():
                return "No results found."
            return result.stdout.replace(notes_dir + "/", "").replace(notes_dir, ".")
        except subprocess.TimeoutExpired:
            return "Error: find timed out after 30 seconds."
        except FileNotFoundError:
            return "Error: find command not found on this system."

    return await asyncio.to_thread(_run_find)


# ---------------------------------------------------------------------------
# Build the ASGI app to be mounted by api.py
#
# We do NOT use mcp.streamable_http_app() because it creates a Starlette
# app whose lifespan (which starts the session manager's task group) does
# NOT fire when mounted inside FastAPI via app.mount().  Instead we:
#   1. Trigger session manager creation via streamable_http_app()
#   2. Build our own Starlette app with the ASGI handler, WITHOUT lifespan
#   3. Manage the session manager lifecycle from api.py startup/shutdown
# ---------------------------------------------------------------------------
from mcp.server.fastmcp.server import StreamableHTTPASGIApp  # noqa: E402
from starlette.applications import Starlette  # noqa: E402
from starlette.routing import Mount, Route  # noqa: E402
from starlette.responses import JSONResponse  # noqa: E402

# Trigger lazy creation of the session manager
mcp.streamable_http_app()

# Build the ASGI handler from the session manager directly
_mcp_handler = StreamableHTTPASGIApp(mcp.session_manager)


# ---------------------------------------------------------------------------
# ASGI wrapper: extract plan_id from ?plan_id=XXX and inject into ContextVar
# ---------------------------------------------------------------------------
class _PlanIdInjectingApp:
    """ASGI middleware that extracts ``plan_id`` from the HTTP query string
    and sets ``_plan_id_ctx`` before delegating to the real MCP handler.

    This ensures every ``@mcp.tool()`` invocation within the request
    automatically resolves to the correct plan namespace without the
    agent needing to pass ``plan_id`` as a tool argument.
    """

    def __init__(self, inner):
        self._inner = inner

    async def __call__(self, scope, receive, send):
        if scope["type"] == "http":
            qs = parse_qs(scope.get("query_string", b"").decode())
            plan_id = qs.get("plan_id", [None])[0]
            token = _plan_id_ctx.set(plan_id)
            try:
                await self._inner(scope, receive, send)
            finally:
                _plan_id_ctx.reset(token)
        else:
            await self._inner(scope, receive, send)


async def _health_endpoint(request):
    """Pool health endpoint at /api/memory-pool/health."""
    pool = _get_pool()
    stats = pool.stats()
    stats["memory_base_dir"] = str(MEMORY_BASE_DIR)
    # List active plan namespaces
    namespaces = []
    if MEMORY_BASE_DIR.is_dir():
        namespaces = sorted(d.name for d in MEMORY_BASE_DIR.iterdir() if d.is_dir())
    stats["namespaces"] = namespaces
    return JSONResponse(stats)


knowledge_mcp_app = Starlette(
    routes=[
        Route("/mcp", endpoint=_PlanIdInjectingApp(_mcp_handler)),
        Route("/health", endpoint=_health_endpoint, methods=["GET"]),
    ],
    # NO lifespan — we manage session_manager lifecycle from api.py
)


# ---------------------------------------------------------------------------
# Session manager lifecycle — called by api.py startup/shutdown
# ---------------------------------------------------------------------------
_session_cm = None


async def startup_knowledge():
    """Start the MCP session manager's task group.  Call from api.py startup."""
    global _session_cm
    _session_cm = mcp.session_manager.run()
    await _session_cm.__aenter__()
    logger.info("Memory Pool MCP session manager started")


async def shutdown_knowledge():
    """Stop the MCP session manager's task group.  Call from api.py shutdown."""
    global _session_cm
    if _session_cm:
        try:
            await _session_cm.__aexit__(None, None, None)
        except Exception:
            logger.exception("Error stopping memory pool session manager")
        _session_cm = None
    # Kill all pool slots
    try:
        pool = _get_pool()
        pool.kill_all()
    except Exception:
        pass
    logger.info("Memory Pool MCP shut down")
